// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Role struct {
	ID   int32
	Name string
}

type User struct {
	ID                int32
	Username          string
	Fullname          string
	Email             string
	HashedPassword    string
	PasswordChangedAt sql.NullTime
	CreatedAt         time.Time
	RoleID            int32
}
