// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Action struct {
	Name string
}

type Policy struct {
	ID       int32
	Subject  string
	Action   string
	Resource string
}

type Resource struct {
	Name     string
	Endpoint string
}

type Role struct {
	Name string
}

type User struct {
	ID                int32
	Username          string
	Fullname          string
	Email             string
	HashedPassword    string
	PasswordChangedAt sql.NullTime
	CreatedAt         time.Time
	Role              string
}
