// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) error
	GetAUser(ctx context.Context, username string) (User, error)
	GetAUserById(ctx context.Context, id int32) (User, error)
	ListPolicies(ctx context.Context) ([]ListPoliciesRow, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
