// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
   "username", "fullname", "email", "hashed_password", "role"
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, username, fullname, email, hashed_password, password_changed_at, created_at, role
`

type CreateUserParams struct {
	Username       string
	Fullname       string
	Email          string
	HashedPassword string
	Role           string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Fullname,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Fullname,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAUser = `-- name: GetAUser :one
SELECT id, username, fullname, email, hashed_password, password_changed_at, created_at, role FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getAUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Fullname,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getAUserById = `-- name: GetAUserById :one
SELECT id, username, fullname, email, hashed_password, password_changed_at, created_at, role FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getAUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Fullname,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT subject, action, resource FROM policies
`

type ListPoliciesRow struct {
	Subject  string
	Action   string
	Resource string
}

func (q *Queries) ListPolicies(ctx context.Context) ([]ListPoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesRow
	for rows.Next() {
		var i ListPoliciesRow
		if err := rows.Scan(&i.Subject, &i.Action, &i.Resource); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, fullname, email, hashed_password, password_changed_at, created_at, role FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Fullname,
			&i.Email,
			&i.HashedPassword,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
