INSERT INTO "professions" ("title") VALUES
  ('{"sk_SK": "Záhradný architekt", "en_US":"Garden architect"}'::JSONB),
  ('{"sk_SK": "Inštalatér", "en_US": "Plumber"}'::JSONB),
  ('{"sk_SK": "Web developer", "en_US": "Web developer"}'::JSONB),
  ('{"sk_SK": "Programátor", "en_US": "Programmer"}'::JSONB),
  ('{"sk_SK": "Učiteľ", "en_US": "Teacher"}'::JSONB),
  ('{"sk_SK": "Lekár", "en_US": "Doctor"}'::JSONB),
  ('{"sk_SK": "Architekt", "en_US": "Architect"}'::JSONB),
  ('{"sk_SK": "Inžinier", "en_US": "Engineer"}'::JSONB),
  ('{"sk_SK": "Advokát", "en_US": "Lawyer"}'::JSONB),
  ('{"sk_SK": "Grafický dizajnér", "en_US": "Graphic Designer"}'::JSONB),
  ('{"sk_SK": "Kuchár", "en_US": "Chef"}'::JSONB),
  ('{"sk_SK": "Elektrikár", "en_US": "Electrician"}'::JSONB),
  ('{"sk_SK": "Obchodný analytik", "en_US": "Business Analyst"}'::JSONB),
  ('{"sk_SK": "Sestra", "en_US": "Nurse"}'::JSONB),
  ('{"sk_SK": "Novinár", "en_US": "Journalist"}'::JSONB),
  ('{"sk_SK": "Archivár", "en_US": "Archivist"}'::JSONB),
  ('{"sk_SK": "Šéfkuchár", "en_US": "Head Chef"}'::JSONB),
  ('{"sk_SK": "Právnik", "en_US": "Attorney"}'::JSONB),
  ('{"sk_SK": "Dizajnér interiérov", "en_US": "Interior Designer"}'::JSONB),
  ('{"sk_SK": "Fotograf", "en_US": "Photographer"}'::JSONB),
  ('{"sk_SK": "Zubár", "en_US": "Dentist"}'::JSONB),
  ('{"sk_SK": "Projektpvý manažér", "en_US": "Project Manager"}'::JSONB),
  ('{"sk_SK": "Veterinár", "en_US": "Veterinarian"}'::JSONB),
  ('{"sk_SK": "Knihovník", "en_US": "Librarian"}'::JSONB),
  ('{"sk_SK": "Umelec", "en_US": "Artist"}'::JSONB),
  ('{"sk_SK": "Pilot", "en_US": "Pilot"}'::JSONB),
  ('{"sk_SK": "Realitný maklér", "en_US": "Real Estate Agent"}'::JSONB),
  ('{"sk_SK": "Fitness inštruktor", "en_US": "Fitness Instructor"}'::JSONB),
  ('{"sk_SK": "Šéf redaktor", "en_US": "Editor-in-Chief"}'::JSONB),
  ('{"sk_SK": "Režisér", "en_US": "Director"}'::JSONB),
  ('{"sk_SK": "Farmaceut", "en_US": "Pharmacist"}'::JSONB),
  ('{"sk_SK": "Grafik", "en_US": "Graphic designer"}'::JSONB),
  ('{"sk_SK": "Poľnohospodár", "en_US": "Farmer"}'::JSONB),
  ('{"sk_SK": "Dátový analytik", "en_US": "Data Analyst"}'::JSONB),
  ('{"sk_SK": "Policajt", "en_US": "Police Officer"}'::JSONB),
  ('{"sk_SK": "Biotechnológ", "en_US": "Biotechnologist"}'::JSONB),
  ('{"sk_SK": "Investičný bankár", "en_US": "Investment Banker"}'::JSONB),
  ('{"sk_SK": "Vedec", "en_US": "Scientist"}'::JSONB),
  ('{"sk_SK": "Florista", "en_US": "Florist"}'::JSONB),
  ('{"sk_SK": "Geodet", "en_US": "Surveyor"}'::JSONB),
  ('{"sk_SK": "Fitness trenér", "en_US": "Fitness Trainer"}'::JSONB),
  ('{"sk_SK": "Štatistik", "en_US": "Statistician"}'::JSONB),
  ('{"sk_SK": "Obchodný manažér", "en_US": "Business Manager"}'::JSONB),
  ('{"sk_SK": "Ekonóm", "en_US": "Economist"}'::JSONB),
  ('{"sk_SK": "Chemik", "en_US": "Chemist"}'::JSONB),
  ('{"sk_SK": "Auto mechanik", "en_US": "Mechanic"}'::JSONB),
  ('{"sk_SK": "Dekoratér interiérov", "en_US": "Interior Decorator"}'::JSONB),
  ('{"sk_SK": "Lingvista", "en_US": "Linguist"}'::JSONB),
  ('{"sk_SK": "Meteorológ", "en_US": "Meteorologist"}'::JSONB),
  ('{"sk_SK": "Zberač odpadkov", "en_US": "Garbage Collector"}'::JSONB),
  ('{"sk_SK": "Vývojár videohier", "en_US": "Video Game Developer"}'::JSONB),
  ('{"sk_SK": "Turistický sprievodca", "en_US": "Tour Guide"}'::JSONB),
  ('{"sk_SK": "Odborník na umelecké diela", "en_US": "Art Conservator"}'::JSONB),
  ('{"sk_SK": "Model", "en_US": "Model"}'::JSONB),
  ('{"sk_SK": "Gurmán", "en_US": "Food Critic"}'::JSONB),
  ('{"sk_SK": "Zvukový inžinier", "en_US": "Sound Engineer"}'::JSONB),
  ('{"sk_SK": "Letový inštruktor", "en_US": "Flight Instructor"}'::JSONB),
  ('{"sk_SK": "Tanečník", "en_US": "Dancer"}'::JSONB),
  ('{"sk_SK": "Redaktor", "en_US": "Editor"}'::JSONB),
  ('{"sk_SK": "Asistent lekára", "en_US": "Medical Assistant"}'::JSONB),
  ('{"sk_SK": "Sociálny pracovník", "en_US": "Social Worker"}'::JSONB),
  ('{"sk_SK": "Strážnik parku", "en_US": "Park Ranger"}'::JSONB),
  ('{"sk_SK": "Riaditeľ obchodu", "en_US": "Store Manager"}'::JSONB),
  ('{"sk_SK": "Výkonný producent filmu", "en_US": "Film Executive Producer"}'::JSONB),
  ('{"sk_SK": "Modelér 3D", "en_US": "3D Modeler"}'::JSONB),
  ('{"sk_SK": "Asistent výskumu a vývoja", "en_US": "Research and Development Assistant"}'::JSONB),
  ('{"sk_SK": "Logistik", "en_US": "Logistician"}'::JSONB),
  ('{"sk_SK": "Ochrana životného prostredia", "en_US": "Environmental Protection Officer"}'::JSONB),
  ('{"sk_SK": "Námorný inžinier", "en_US": "Marine Engineer"}'::JSONB),
  ('{"sk_SK": "Módny návrhár", "en_US": "Fashion Designer"}'::JSONB),
  ('{"sk_SK": "Manažér ľudských zdrojov", "en_US": "Human Resources Manager"}'::JSONB),
  ('{"sk_SK": "Investičný poradca", "en_US": "Investment Advisor"}'::JSONB),
  ('{"sk_SK": "Záchranár", "en_US": "Paramedic"}'::JSONB),
  ('{"sk_SK": "Filmový producent", "en_US": "Film Producer"}'::JSONB),
  ('{"sk_SK": "Notár", "en_US": "Notary"}'::JSONB),
  ('{"sk_SK": "Zdravotná sestra", "en_US": "Health Nurse"}'::JSONB),
  ('{"sk_SK": "Projektový inžinier", "en_US": "Project Engineer"}'::JSONB),
  ('{"sk_SK": "Výskumník", "en_US": "Researcher"}'::JSONB),
  ('{"sk_SK": "Zubný technik", "en_US": "Dental Technician"}'::JSONB),
  ('{"sk_SK": "Finančný poradca", "en_US": "Financial Advisor"}'::JSONB),
  ('{"sk_SK": "Strieborný hrnčiar", "en_US": "Silversmith"}'::JSONB),
  ('{"sk_SK": "Tesár", "en_US": "Carpenter"}'::JSONB),
  ('{"sk_SK": "Murár", "en_US": "Bricklayer"}'::JSONB),
  ('{"sk_SK": "Kováč", "en_US": "Blacksmith"}'::JSONB),
  ('{"sk_SK": "Kamenár", "en_US": "Stone Mason"}'::JSONB),
  ('{"sk_SK": "Tkáč", "en_US": "Weaver"}'::JSONB),
  ('{"sk_SK": "Zlatník", "en_US": "Goldsmith"}'::JSONB),
  ('{"sk_SK": "Šička", "en_US": "Seamstress"}'::JSONB),
  ('{"sk_SK": "Keramik", "en_US": "Ceramicist"}'::JSONB),
  ('{"sk_SK": "Obkladač", "en_US": "Tiler"}'::JSONB),
  ('{"sk_SK": "Stolár", "en_US": "Joiner"}'::JSONB),
  ('{"sk_SK": "Krajčír", "en_US": "Tailor"}'::JSONB),
  ('{"sk_SK": "Kaderník", "en_US": "Hairdresser"}'::JSONB),
  ('{"sk_SK": "Maliar", "en_US": "Painter"}'::JSONB);

CREATE EXTENSION IF NOT EXISTS unaccent;