server {
     server_name $SERVER_NAME;
     index wip.html;
     listen [::]:80;
     listen 80;
     location / {
         root   /usr/share/nginx/html;
         try_files $%uri $%uri/ /wip.html;
     }

}