server {
     server_name $SERVER_NAME;
     listen [::]:80;
     listen 80;
     client_max_body_size 20M;

     location / {
         root   /usr/share/nginx/html;
         try_files $%uri $%uri/ /index.html;
     }
     location /api {
         rewrite ^/api(/.*)$ $1 break;
         proxy_pass http://$API_HOST:$API_PORT;
         proxy_set_header Host $API_HOST;
         proxy_set_header X-Real-IP $%remote_addr;
         proxy_set_header X-Forwarded-For $%proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $%scheme;
     }
     location /adminer {
         rewrite ^/adminer(/.*)$ $1 break;
         proxy_pass http://adminer:8080;
         proxy_set_header Host adminer;
         proxy_set_header X-Real-IP $%remote_addr;
         proxy_set_header X-Forwarded-For $%proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $%scheme;
     }
     location /media {
         proxy_pass http://$MEDIA_STORE_HOST:$MEDIA_STORE_PORT;
         proxy_set_header Host $MEDIA_STORE_HOST;
         proxy_set_header X-Real-IP $%remote_addr;
         proxy_set_header X-Forwarded-For $%proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $%scheme;
     }

     if ($http_user_agent ~* "facebookexternalhit/1.1") {
        rewrite ^(.*)$ /usr/share/nginx/html/fb.html;
     }

}